# Generated by Django 5.2.8 on 2026-10-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_jobpostmodel_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('Recruiter', 'Recruiter'), ('Seeker', 'Seeker')], default='Seeker', max_length=100, null=True),
        ),
    ]
